"""
train_lnn_fixed.py
------------------
Lagrangian Neural Network training for the 2D rigid-body spring
collision dataset generated by rb_spring_collision.ipynb.

The dataset contains the state of two rigid bodies (blade end-effector
and target) during spring-based contact. The system has 6 generalized
coordinates: q = (x_ee, y_ee, phi_ee, x_targ, y_targ, phi_targ).

Since the dataset only contains contact-phase data, a single LNN is
trained on all samples. Accelerations are computed via finite differences
from the velocity data at consecutive time steps:

    q̈ ≈ (q̇(t+dt) - q̇(t)) / dt

Usage:
    # First run rb_spring_collision.ipynb to generate
    # master_training_dataset.csv, then:
    python3 train_lnn_fixed.py

Outputs:
    lnn_contact.pth          — learned Lagrangian for contact phase
    lnn_training_curves.png
"""

from __future__ import annotations

import argparse
from pathlib import Path

import numpy as np
import pandas as pd
import torch
import torch.nn as nn
import torch.optim as optim
from torch.func import hessian, jacrev, vmap
from torch.utils.data import DataLoader, TensorDataset


# ---------------------------------------------------------------------------
# Model
# ---------------------------------------------------------------------------

class LagrangianNet(nn.Module):
    """
    Scalar-output network that parameterizes the Lagrangian L(q, q̇).

    Softplus activation (not ReLU) because we need smooth 2nd derivatives
    through autograd — ReLU's kink makes the Hessian ill-defined.
    """

    def __init__(self, n_q: int, hidden: int = 128):
        super().__init__()
        self.net = nn.Sequential(
            nn.Linear(2 * n_q, hidden),
            nn.Softplus(),
            nn.Linear(hidden, hidden),
            nn.Softplus(),
            nn.Linear(hidden, hidden // 2),
            nn.Softplus(),
            nn.Linear(hidden // 2, 1),
        )

    def forward(self, q_qdot: torch.Tensor) -> torch.Tensor:
        # q_qdot: (2*n_q,) → scalar
        return self.net(q_qdot).squeeze(-1)


# ---------------------------------------------------------------------------
# Physics: Euler-Lagrange → accelerations
# ---------------------------------------------------------------------------

def make_lagrangian_dynamics(model: LagrangianNet):
    """
    Given an LNN that maps [q, q̇] → scalar L, return a function
    (q, q̇) → q̈ implementing:

        M q̈ + C q̇ = ∂L/∂q

        where
            M = ∂²L/∂q̇²                 (mass matrix)
            C_ij = ∂²L / (∂q̇_i ∂q_j)    (Coriolis-ish)

        ⇒  q̈ = M⁻¹ (∂L/∂q − C q̇)

    Uses `torch.func` so the whole thing vmaps cleanly over a batch.
    """

    def L_of_q_qdot(q: torch.Tensor, q_dot: torch.Tensor) -> torch.Tensor:
        return model(torch.cat([q, q_dot]))

    # Gradient of L w.r.t. q (keeps q̇ fixed): shape (n_q,)
    dL_dq_fn = jacrev(L_of_q_qdot, argnums=0)

    # Mass matrix M = ∂²L/∂q̇² (Hessian w.r.t. q̇): shape (n_q, n_q)
    M_fn = hessian(L_of_q_qdot, argnums=1)

    # Mixed partial C = ∂²L/(∂q̇ ∂q): Jacobian of (∂L/∂q̇) w.r.t. q
    dL_dqdot_fn = jacrev(L_of_q_qdot, argnums=1)
    C_fn = jacrev(dL_dqdot_fn, argnums=0)  # shape (n_q, n_q)

    def q_ddot_single(q: torch.Tensor, q_dot: torch.Tensor) -> torch.Tensor:
        dL_dq = dL_dq_fn(q, q_dot)
        M = M_fn(q, q_dot)
        C = C_fn(q, q_dot)

        rhs = dL_dq - C @ q_dot
        # linalg.solve is more stable than inv(M) @ rhs
        try:
            q_ddot = torch.linalg.solve(M, rhs)
        except RuntimeError:
            q_ddot = torch.linalg.pinv(M) @ rhs
        return q_ddot

    return vmap(q_ddot_single)


# ---------------------------------------------------------------------------
# Data
# ---------------------------------------------------------------------------

# Dataset columns from rb_spring_collision.ipynb:
# The generalized coordinates q = (x_ee, y_ee, phi_ee, x_targ, y_targ, phi_targ)
# and their velocities.
Q_COLS     = ["in_x_ee",  "in_y_ee",  "in_phi_ee",
              "in_x_targ",  "in_y_targ",  "in_phi_targ"]
QDOT_COLS  = ["in_vx_ee", "in_vy_ee", "in_vphi_ee",
              "in_vx_targ", "in_vy_targ", "in_vphi_targ"]
# Output velocities at t+dt — used to compute accelerations via finite differences
QDOT_OUT_COLS = ["out_vx_ee", "out_vy_ee", "out_vphi_ee",
                 "out_vx_targ", "out_vy_targ", "out_vphi_targ"]
DT_COL = "dt"


def load_data(csv_path: Path):
    """
    Load the dataset generated by rb_spring_collision.ipynb.

    Since the notebook does not output accelerations directly, they are
    computed via finite differences:
        q̈ ≈ (q̇(t+dt) - q̇(t)) / dt

    Per-feature normalization is applied so each column is scaled to
    roughly [-1, 1].  This is critical because the stiff spring system
    produces accelerations spanning many orders of magnitude (e.g.
    phi_targ accel ~ 1e8 while y_targ accel ~ 1).  Without this the
    network instantly diverges to NaN.

    Returns:
        (q, qdot, qddot, scales) — tensors + dict of scale factors
    """
    df = pd.read_csv(csv_path)

    q_raw     = torch.tensor(df[Q_COLS].values,     dtype=torch.float32)
    qdot_raw  = torch.tensor(df[QDOT_COLS].values,  dtype=torch.float32)

    # Compute accelerations from finite differences
    qdot_out = torch.tensor(df[QDOT_OUT_COLS].values, dtype=torch.float32)
    dt = torch.tensor(df[DT_COL].values, dtype=torch.float32).unsqueeze(-1)
    qddot_raw = (qdot_out - qdot_raw) / dt

    # --- per-feature normalization (divide by max|value| per column) ---
    def norm_scale(tensor):
        s = tensor.abs().max(dim=0).values.clamp(min=1e-12)
        return tensor / s, s

    q,     q_scale     = norm_scale(q_raw)
    qdot,  qdot_scale  = norm_scale(qdot_raw)
    qddot, qddot_scale = norm_scale(qddot_raw)

    # Remove any remaining NaN/Inf rows (safety net)
    valid = torch.isfinite(q).all(1) & torch.isfinite(qdot).all(1) & torch.isfinite(qddot).all(1)
    if (~valid).any():
        print(f"[data] dropping {(~valid).sum().item()} non-finite rows")
        q, qdot, qddot = q[valid], qdot[valid], qddot[valid]

    scales = {"q": q_scale, "qdot": qdot_scale, "qddot": qddot_scale}

    print(f"[data] loaded {len(q)} contact samples (normalised)")
    print(f"[data] q scale:     {q_scale.tolist()}")
    print(f"[data] qdot scale:  {qdot_scale.tolist()}")
    print(f"[data] qddot scale: {qddot_scale.tolist()}")

    return q, qdot, qddot, scales


def make_loaders(q, qdot, qddot, batch_size=128, train_frac=0.8, seed=0):
    n = len(q)
    g = torch.Generator().manual_seed(seed)
    perm = torch.randperm(n, generator=g)
    n_train = int(train_frac * n)

    def subset(idx):
        return TensorDataset(q[idx], qdot[idx], qddot[idx])

    train_ds = subset(perm[:n_train])
    test_ds  = subset(perm[n_train:])
    train_loader = DataLoader(train_ds, batch_size=batch_size, shuffle=True, generator=g)
    test_loader  = DataLoader(test_ds,  batch_size=256, shuffle=False)
    return train_loader, test_loader


# ---------------------------------------------------------------------------
# Training
# ---------------------------------------------------------------------------

def train_one(
    name: str,
    q, qdot, qddot,
    epochs: int = 500,
    lr: float = 1e-4,
    hidden: int = 128,
    batch_size: int = 128,
    device: str = "cpu",
):
    n_q = q.shape[1]
    model = LagrangianNet(n_q=n_q, hidden=hidden).to(device)
    dynamics = make_lagrangian_dynamics(model)
    optimizer = optim.Adam(model.parameters(), lr=lr)
    loss_fn = nn.MSELoss()

    train_loader, test_loader = make_loaders(q, qdot, qddot, batch_size=batch_size)

    train_hist, test_hist = [], []
    print(f"\n[train:{name}] starting — epochs={epochs}, lr={lr}, hidden={hidden}, n_q={n_q}")

    for epoch in range(1, epochs + 1):
        # ---- train ----
        model.train()
        batch_losses = []
        for q_b, qdot_b, qddot_b in train_loader:
            q_b, qdot_b, qddot_b = q_b.to(device), qdot_b.to(device), qddot_b.to(device)
            optimizer.zero_grad()
            pred = dynamics(q_b, qdot_b)
            loss = loss_fn(pred, qddot_b)
            loss.backward()
            # Clip hard — LNN gradients can spike when M is near-singular
            torch.nn.utils.clip_grad_norm_(model.parameters(), max_norm=1.0)
            optimizer.step()
            batch_losses.append(loss.item())
        train_loss = float(np.mean(batch_losses))

        # ---- eval ----
        model.eval()
        test_losses = []
        # Note: we CAN'T use torch.no_grad() here — the autograd machinery
        # inside dynamics(...) still needs grad tracking through inputs.
        for q_b, qdot_b, qddot_b in test_loader:
            q_b, qdot_b, qddot_b = q_b.to(device), qdot_b.to(device), qddot_b.to(device)
            pred = dynamics(q_b, qdot_b)
            test_losses.append(loss_fn(pred, qddot_b).item())
        test_loss = float(np.mean(test_losses))

        train_hist.append(train_loss)
        test_hist.append(test_loss)

        if epoch % 10 == 0 or epoch == 1:
            print(f"[train:{name}] epoch {epoch:>3d}/{epochs}  "
                  f"train={train_loss:.4e}  test={test_loss:.4e}")

    return model, train_hist, test_hist


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------

def plot_curves(curves: dict, out_path: Path):
    # Imported lazily so the training script works in headless environments
    import matplotlib
    matplotlib.use("Agg")
    import matplotlib.pyplot as plt

    n_plots = len(curves)
    fig, axes = plt.subplots(1, n_plots, figsize=(6 * n_plots, 4), sharey=True,
                             squeeze=False)
    for ax, (name, hist) in zip(axes[0], curves.items()):
        ax.plot(hist["train"], label="train")
        ax.plot(hist["test"],  label="test")
        ax.set_title(name)
        ax.set_xlabel("epoch")
        ax.set_ylabel("MSE (physical units)")
        ax.set_yscale("log")
        ax.grid(True, alpha=0.3)
        ax.legend()
    fig.tight_layout()
    fig.savefig(out_path, dpi=120)
    print(f"[plot] saved {out_path}")


def main():
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--csv", type=Path, default=Path("master_training_dataset.csv"),
                        help="Path to the dataset CSV (default: ./master_training_dataset.csv)")
    parser.add_argument("--epochs", type=int, default=300)
    parser.add_argument("--lr", type=float, default=1e-4)
    parser.add_argument("--hidden", type=int, default=128)
    parser.add_argument("--batch-size", type=int, default=128)
    parser.add_argument("--device", default="cuda" if torch.cuda.is_available() else "cpu")
    parser.add_argument("--out-dir", type=Path, default=Path("."))
    args = parser.parse_args()

    if not args.csv.exists():
        raise FileNotFoundError(
            f"Dataset not found at {args.csv}. "
            f"Run rb_spring_collision.ipynb first to generate it."
        )

    print(f"[main] device = {args.device}")
    q, qdot, qddot, scales = load_data(args.csv)

    curves = {}

    model, tr, te = train_one(
        "contact", q, qdot, qddot,
        epochs=args.epochs, lr=args.lr, hidden=args.hidden,
        batch_size=args.batch_size, device=args.device,
    )
    # Save model weights + normalization scales together
    torch.save({
        "model_state_dict": model.state_dict(),
        "scales": scales,
    }, args.out_dir / "lnn_contact.pth")
    print(f"[main] saved {args.out_dir / 'lnn_contact.pth'}")
    curves["contact"] = {"train": tr, "test": te}

    plot_curves(curves, args.out_dir / "lnn_training_curves.png")

    print("\n[main] done.")
    print("  Load with:")
    print("      checkpoint = torch.load('lnn_contact.pth')")
    print("      model = LagrangianNet(n_q=6)")
    print("      model.load_state_dict(checkpoint['model_state_dict'])")
    print("      scales = checkpoint['scales']  # normalisation factors")
    print("      dynamics = make_lagrangian_dynamics(model)")
    print("      q_ddot = dynamics(q_batch, qdot_batch)")


if __name__ == "__main__":
    main()
